### ISSUE TITLE
Relative path is not applied on generated links

### ISSUE THREAD

**Issue by bpkinez** [nareshbhatia/mobx-state-router-examples#1]
Hi Naresh,

There is a small issue with internal links. When relative path is set, everything works fine but generated links do not have "/myapp" in their structure. Is there any workaround to solve this, or this is normal behaviour? I think there should be consistency between basename path setup and generated links. To better understand issue look at the image below:

![relative-path-links-issue](https://user-images.githubusercontent.com/7535133/47362238-442cd600-d6d4-11e8-8be3-00f0d7ff938e.png)

**Comment by nareshbhatia** [comment]
That's a good catch! I suspect this will require us to configure the router with a basename so that [generateUrl()](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/adapters/generate-url.ts#L29-L40) can produce the right URL. Can you think of a better solution?

**Comment by bpkinez** [comment]
I solved this with some tweaking in routes.js. E.g.: 

```js
const routesConfig = [
  /* home route */
  {
    name: 'home',
    pattern: '/'
  },
  /* about route */
  {
    name: 'about',
    pattern: '/about'
  },
  /* contact route */
  {
    name: 'contact',
    pattern: '/contact'
  },
  /* not found route */
  {
    name: 'notFound',
    pattern: '/not-found'
  }
];

export const routes = routesConfig.map(route => ({
  ...route,
  pattern: `${process.env.PUBLIC_URL}${route.pattern}`
}));
```

but I think that will be better to configure router with a basename instead of tweaking routes.

**Comment by nareshbhatia** [comment]
Very clever! I will add a feature request to mobx-state-router project to add basename as a configuration parameter.
